### ISSUE TITLE
iangraham20 (igc2) lab11 - Issues

### ISSUE THREAD

**Issue by iangraham20** [CS262E-Pilot/Knight-Ranker-App#41]
For lab 11:
Reformat Code -> Optimize Imports & Rearrange Entries
- Removed empty stub methods
- Deleted unecessary spaces
- There were some usability and security issues

Updates included
- Refactored package name
- Modified layouts to use Relative rather than Grid/Constraint
- Fixed some bugs I didn't really understand

**Comment by J-Jinn** [comment]
You forgot to close the issue =P

**Comment by iangraham20** [comment]
Oops, thanks Jo! Sorry about that.
